name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/workflows/**'
      - '*dockerfile'
      - 'modules/**'
      - '**.tf'
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan       

  terraform_apply:
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_NAME: ${{ secrets.ECRREPO_NAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply 

    docker_build:
    docker build -t samrdaymondweatherapp -f ./weather-app.dockerfile

    docker_tag:
    docker tag samrdaymondweatherapp:1 {account-id}.dkr.ecr.{aws-region}.amazonaws.com/{repo-name}:1

    ecr_login:
    aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin {account-id}.dkr.ecr.{aws-region}.amazonaws.com

    docker_push:
    docker push {account-id}.dkr.ecr.{aws-region}.amazonaws.com/{repo-name}:1





